"""add_customer_requirement_tables

Revision ID: 2572548d4dc7
Revises: 43051d327276
Create Date: 2026-02-03 09:16:30.618794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2572548d4dc7'
down_revision: Union[str, None] = '43051d327276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=500), nullable=True),
    sa.Column('address_line2', sa.String(length=500), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(length=50), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.Column('phone_ext', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_ext', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('best_time_call', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=100), nullable=True),
    sa.Column('branch_office', sa.String(length=255), nullable=True),
    sa.Column('no_of_employees', sa.Integer(), nullable=True),
    sa.Column('instance_required', sa.String(length=100), nullable=True),
    sa.Column('ecommerce', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('timezone_id', sa.Integer(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('lead_source_id', sa.Integer(), nullable=True),
    sa.Column('lead_from_id', sa.Integer(), nullable=True),
    sa.Column('lead_from_name', sa.String(length=255), nullable=True),
    sa.Column('lead_score', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('office_timing_from', sa.String(length=20), nullable=True),
    sa.Column('office_timing_to', sa.String(length=20), nullable=True),
    sa.Column('need_type', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('time_frame', sa.String(length=100), nullable=True),
    sa.Column('current_it_infrastructure', sa.Text(), nullable=True),
    sa.Column('current_software', sa.String(length=255), nullable=True),
    sa.Column('need_summary', sa.Text(), nullable=True),
    sa.Column('decision_maker', sa.String(length=255), nullable=True),
    sa.Column('qualified_by', sa.String(length=255), nullable=True),
    sa.Column('company_profile', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('current_tab', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_requirements_id'), 'customer_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_customer_requirements_lead_id'), 'customer_requirements', ['lead_id'], unique=False)
    op.create_table('cr_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_activities_customer_requirement_id'), 'cr_activities', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_activities_id'), 'cr_activities', ['id'], unique=False)
    op.create_table('cr_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('agreement_number', sa.String(length=100), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('agreement_type', sa.String(length=100), nullable=True),
    sa.Column('agreement_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('special_conditions', sa.Text(), nullable=True),
    sa.Column('signed_by_customer', sa.Boolean(), nullable=True),
    sa.Column('signed_by_company', sa.Boolean(), nullable=True),
    sa.Column('customer_signatory', sa.String(length=255), nullable=True),
    sa.Column('company_signatory', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_agreements_customer_requirement_id'), 'cr_agreements', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_agreements_id'), 'cr_agreements', ['id'], unique=False)
    op.create_table('cr_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('call_time', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('caller_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_call_logs_customer_requirement_id'), 'cr_call_logs', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_call_logs_id'), 'cr_call_logs', ['id'], unique=False)
    op.create_table('cr_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=255), nullable=True),
    sa.Column('instance_url', sa.String(length=500), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('modules_configured', sa.Text(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('customizations', sa.Text(), nullable=True),
    sa.Column('integrations', sa.Text(), nullable=True),
    sa.Column('configured_by', sa.Integer(), nullable=True),
    sa.Column('configuration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_configurations_customer_requirement_id'), 'cr_configurations', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_configurations_id'), 'cr_configurations', ['id'], unique=False)
    op.create_table('cr_data_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('migration_date', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=255), nullable=True),
    sa.Column('target_system', sa.String(length=255), nullable=True),
    sa.Column('data_mapping', sa.Text(), nullable=True),
    sa.Column('migration_scripts', sa.Text(), nullable=True),
    sa.Column('records_migrated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('validation_results', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('migrated_by', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_data_migrations_customer_requirement_id'), 'cr_data_migrations', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_data_migrations_id'), 'cr_data_migrations', ['id'], unique=False)
    op.create_table('cr_demos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('demo_date', sa.Date(), nullable=True),
    sa.Column('demo_time', sa.String(length=50), nullable=True),
    sa.Column('demo_type', sa.String(length=100), nullable=True),
    sa.Column('presenter_id', sa.Integer(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('modules_to_demo', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_demos_customer_requirement_id'), 'cr_demos', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_demos_id'), 'cr_demos', ['id'], unique=False)
    op.create_table('cr_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('sub_tab_name', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_documents_customer_requirement_id'), 'cr_documents', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_documents_id'), 'cr_documents', ['id'], unique=False)
    op.create_table('cr_go_lives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('planned_go_live_date', sa.Date(), nullable=True),
    sa.Column('actual_go_live_date', sa.Date(), nullable=True),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('pre_go_live_tasks', sa.Text(), nullable=True),
    sa.Column('post_go_live_tasks', sa.Text(), nullable=True),
    sa.Column('deployment_notes', sa.Text(), nullable=True),
    sa.Column('issues_encountered', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_go_lives_customer_requirement_id'), 'cr_go_lives', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_go_lives_id'), 'cr_go_lives', ['id'], unique=False)
    op.create_table('cr_initiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_code', sa.String(length=100), nullable=True),
    sa.Column('kickoff_date', sa.Date(), nullable=True),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.Column('team_members', sa.Text(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('scope_statement', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_initiations_customer_requirement_id'), 'cr_initiations', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_initiations_id'), 'cr_initiations', ['id'], unique=False)
    op.create_table('cr_introductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('contact_ids', sa.Text(), nullable=True),
    sa.Column('email_format', sa.String(length=100), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_introductions_customer_requirement_id'), 'cr_introductions', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_introductions_id'), 'cr_introductions', ['id'], unique=False)
    op.create_table('cr_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_memos_customer_requirement_id'), 'cr_memos', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_memos_id'), 'cr_memos', ['id'], unique=False)
    op.create_table('cr_plannings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('work_breakdown', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('risk_plan', sa.Text(), nullable=True),
    sa.Column('communication_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_plannings_customer_requirement_id'), 'cr_plannings', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_plannings_id'), 'cr_plannings', ['id'], unique=False)
    op.create_table('cr_presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('presentation_date', sa.Date(), nullable=True),
    sa.Column('presentation_time', sa.String(length=50), nullable=True),
    sa.Column('presenter_id', sa.Integer(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_presentations_customer_requirement_id'), 'cr_presentations', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_presentations_id'), 'cr_presentations', ['id'], unique=False)
    op.create_table('cr_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('proposal_number', sa.String(length=100), nullable=True),
    sa.Column('proposal_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_proposals_customer_requirement_id'), 'cr_proposals', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_proposals_id'), 'cr_proposals', ['id'], unique=False)
    op.create_table('cr_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('software_type', sa.String(length=100), nullable=True),
    sa.Column('modules_required', sa.Text(), nullable=True),
    sa.Column('ecommerce_required', sa.Boolean(), nullable=True),
    sa.Column('ecommerce_modules', sa.Text(), nullable=True),
    sa.Column('business_analysis', sa.Text(), nullable=True),
    sa.Column('functional_analysis', sa.Text(), nullable=True),
    sa.Column('software_analysis', sa.Text(), nullable=True),
    sa.Column('process_flow_diagram', sa.Text(), nullable=True),
    sa.Column('process_flow_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_requirements_customer_requirement_id'), 'cr_requirements', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_requirements_id'), 'cr_requirements', ['id'], unique=False)
    op.create_table('cr_status_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_status_histories_customer_requirement_id'), 'cr_status_histories', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_status_histories_id'), 'cr_status_histories', ['id'], unique=False)
    op.create_table('cr_supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('support_start_date', sa.Date(), nullable=True),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('support_type', sa.String(length=100), nullable=True),
    sa.Column('sla_response_time', sa.String(length=50), nullable=True),
    sa.Column('sla_resolution_time', sa.String(length=50), nullable=True),
    sa.Column('support_hours', sa.String(length=100), nullable=True),
    sa.Column('support_channels', sa.Text(), nullable=True),
    sa.Column('escalation_matrix', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_supports_customer_requirement_id'), 'cr_supports', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_supports_id'), 'cr_supports', ['id'], unique=False)
    op.create_table('cr_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.String(length=100), nullable=True),
    sa.Column('training_date', sa.Date(), nullable=True),
    sa.Column('training_time', sa.String(length=50), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('trainees', sa.Text(), nullable=True),
    sa.Column('topics_covered', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_trainings_customer_requirement_id'), 'cr_trainings', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_trainings_id'), 'cr_trainings', ['id'], unique=False)
    op.create_table('cr_uats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('uat_start_date', sa.Date(), nullable=True),
    sa.Column('uat_end_date', sa.Date(), nullable=True),
    sa.Column('test_scenarios', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.Text(), nullable=True),
    sa.Column('testers', sa.Text(), nullable=True),
    sa.Column('issues_found', sa.Text(), nullable=True),
    sa.Column('issues_resolved', sa.Text(), nullable=True),
    sa.Column('sign_off_date', sa.Date(), nullable=True),
    sa.Column('signed_off_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_requirement_id'], ['customer_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cr_uats_customer_requirement_id'), 'cr_uats', ['customer_requirement_id'], unique=False)
    op.create_index(op.f('ix_cr_uats_id'), 'cr_uats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cr_uats_id'), table_name='cr_uats')
    op.drop_index(op.f('ix_cr_uats_customer_requirement_id'), table_name='cr_uats')
    op.drop_table('cr_uats')
    op.drop_index(op.f('ix_cr_trainings_id'), table_name='cr_trainings')
    op.drop_index(op.f('ix_cr_trainings_customer_requirement_id'), table_name='cr_trainings')
    op.drop_table('cr_trainings')
    op.drop_index(op.f('ix_cr_supports_id'), table_name='cr_supports')
    op.drop_index(op.f('ix_cr_supports_customer_requirement_id'), table_name='cr_supports')
    op.drop_table('cr_supports')
    op.drop_index(op.f('ix_cr_status_histories_id'), table_name='cr_status_histories')
    op.drop_index(op.f('ix_cr_status_histories_customer_requirement_id'), table_name='cr_status_histories')
    op.drop_table('cr_status_histories')
    op.drop_index(op.f('ix_cr_requirements_id'), table_name='cr_requirements')
    op.drop_index(op.f('ix_cr_requirements_customer_requirement_id'), table_name='cr_requirements')
    op.drop_table('cr_requirements')
    op.drop_index(op.f('ix_cr_proposals_id'), table_name='cr_proposals')
    op.drop_index(op.f('ix_cr_proposals_customer_requirement_id'), table_name='cr_proposals')
    op.drop_table('cr_proposals')
    op.drop_index(op.f('ix_cr_presentations_id'), table_name='cr_presentations')
    op.drop_index(op.f('ix_cr_presentations_customer_requirement_id'), table_name='cr_presentations')
    op.drop_table('cr_presentations')
    op.drop_index(op.f('ix_cr_plannings_id'), table_name='cr_plannings')
    op.drop_index(op.f('ix_cr_plannings_customer_requirement_id'), table_name='cr_plannings')
    op.drop_table('cr_plannings')
    op.drop_index(op.f('ix_cr_memos_id'), table_name='cr_memos')
    op.drop_index(op.f('ix_cr_memos_customer_requirement_id'), table_name='cr_memos')
    op.drop_table('cr_memos')
    op.drop_index(op.f('ix_cr_introductions_id'), table_name='cr_introductions')
    op.drop_index(op.f('ix_cr_introductions_customer_requirement_id'), table_name='cr_introductions')
    op.drop_table('cr_introductions')
    op.drop_index(op.f('ix_cr_initiations_id'), table_name='cr_initiations')
    op.drop_index(op.f('ix_cr_initiations_customer_requirement_id'), table_name='cr_initiations')
    op.drop_table('cr_initiations')
    op.drop_index(op.f('ix_cr_go_lives_id'), table_name='cr_go_lives')
    op.drop_index(op.f('ix_cr_go_lives_customer_requirement_id'), table_name='cr_go_lives')
    op.drop_table('cr_go_lives')
    op.drop_index(op.f('ix_cr_documents_id'), table_name='cr_documents')
    op.drop_index(op.f('ix_cr_documents_customer_requirement_id'), table_name='cr_documents')
    op.drop_table('cr_documents')
    op.drop_index(op.f('ix_cr_demos_id'), table_name='cr_demos')
    op.drop_index(op.f('ix_cr_demos_customer_requirement_id'), table_name='cr_demos')
    op.drop_table('cr_demos')
    op.drop_index(op.f('ix_cr_data_migrations_id'), table_name='cr_data_migrations')
    op.drop_index(op.f('ix_cr_data_migrations_customer_requirement_id'), table_name='cr_data_migrations')
    op.drop_table('cr_data_migrations')
    op.drop_index(op.f('ix_cr_configurations_id'), table_name='cr_configurations')
    op.drop_index(op.f('ix_cr_configurations_customer_requirement_id'), table_name='cr_configurations')
    op.drop_table('cr_configurations')
    op.drop_index(op.f('ix_cr_call_logs_id'), table_name='cr_call_logs')
    op.drop_index(op.f('ix_cr_call_logs_customer_requirement_id'), table_name='cr_call_logs')
    op.drop_table('cr_call_logs')
    op.drop_index(op.f('ix_cr_agreements_id'), table_name='cr_agreements')
    op.drop_index(op.f('ix_cr_agreements_customer_requirement_id'), table_name='cr_agreements')
    op.drop_table('cr_agreements')
    op.drop_index(op.f('ix_cr_activities_id'), table_name='cr_activities')
    op.drop_index(op.f('ix_cr_activities_customer_requirement_id'), table_name='cr_activities')
    op.drop_table('cr_activities')
    op.drop_index(op.f('ix_customer_requirements_lead_id'), table_name='customer_requirements')
    op.drop_index(op.f('ix_customer_requirements_id'), table_name='customer_requirements')
    op.drop_table('customer_requirements')
    # ### end Alembic commands ###
