"""add source column to cr_activities

Revision ID: 366bc376ae4b
Revises: k5l6m7n8o9p0
Create Date: 2026-02-12 16:21:16.798207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366bc376ae4b'
down_revision: Union[str, None] = 'k5l6m7n8o9p0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_activities', sa.Column('source', sa.String(length=100), nullable=True))
    op.drop_index('ix_cri_email_templates_company_id', table_name='cri_email_templates')
    op.drop_index('ix_cri_email_templates_tab', table_name='cri_email_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cri_email_templates_tab', 'cri_email_templates', ['tab'], unique=False)
    op.create_index('ix_cri_email_templates_company_id', 'cri_email_templates', ['company_id'], unique=False)
    op.drop_column('cr_activities', 'source')
    # ### end Alembic commands ###
