"""Add new string fields to sales_targets

Revision ID: 43051d327276
Revises: c84ac7e1ba32
Create Date: 2026-02-02 11:52:23.153003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43051d327276'
down_revision: Union[str, None] = 'c84ac7e1ba32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use IF NOT EXISTS to handle columns already created by the initial migration
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS designation VARCHAR(100)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS reporting_to VARCHAR(255)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS region VARCHAR(100)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS frequency VARCHAR(50)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS stage VARCHAR(100)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS sales_type VARCHAR(50)")
    op.execute("ALTER TABLE sales_targets ADD COLUMN IF NOT EXISTS remarks VARCHAR(500)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_targets', 'remarks')
    op.drop_column('sales_targets', 'sales_type')
    op.drop_column('sales_targets', 'stage')
    op.drop_column('sales_targets', 'frequency')
    op.drop_column('sales_targets', 'region')
    op.drop_column('sales_targets', 'reporting_to')
    op.drop_column('sales_targets', 'designation')
    # ### end Alembic commands ###
