"""Add new string fields to sales_targets

Revision ID: 43051d327276
Revises: c84ac7e1ba32
Create Date: 2026-02-02 11:52:23.153003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43051d327276'
down_revision: Union[str, None] = 'c84ac7e1ba32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_targets', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('sales_targets', sa.Column('reporting_to', sa.String(length=255), nullable=True))
    op.add_column('sales_targets', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('sales_targets', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.add_column('sales_targets', sa.Column('stage', sa.String(length=100), nullable=True))
    op.add_column('sales_targets', sa.Column('sales_type', sa.String(length=50), nullable=True))
    op.add_column('sales_targets', sa.Column('remarks', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_targets', 'remarks')
    op.drop_column('sales_targets', 'sales_type')
    op.drop_column('sales_targets', 'stage')
    op.drop_column('sales_targets', 'frequency')
    op.drop_column('sales_targets', 'region')
    op.drop_column('sales_targets', 'reporting_to')
    op.drop_column('sales_targets', 'designation')
    # ### end Alembic commands ###
