"""Add new pre_lead fields

Revision ID: 69e6232e176c
Revises: 
Create Date: 2026-01-27 18:54:47.144575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e6232e176c'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_leads', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('pre_leads', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('pre_leads', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('pre_leads', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('phone_no', sa.String(length=50), nullable=True))
    op.add_column('pre_leads', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('pre_leads', sa.Column('nof_representative', sa.String(length=255), nullable=True))
    op.add_column('pre_leads', sa.Column('memo', sa.Text(), nullable=True))
    op.add_column('pre_leads', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('lead_status', sa.String(length=50), nullable=True))
    op.add_column('pre_leads', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('office_timings', sa.String(length=100), nullable=True))
    op.add_column('pre_leads', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('pre_leads', sa.Column('lead_source', sa.String(length=100), nullable=True))
    op.add_column('pre_leads', sa.Column('sales_rep', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('lead_since', sa.Date(), nullable=True))
    op.add_column('pre_leads', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('pre_leads', sa.Column('lead_score', sa.String(length=50), nullable=True))
    op.add_column('pre_leads', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('createdby', sa.Integer(), nullable=True))
    op.add_column('pre_leads', sa.Column('updatedby', sa.Integer(), nullable=True))
    op.alter_column('pre_leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('pre_leads', 'alternate_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_leads', 'alternate_phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('pre_leads', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('pre_leads', 'updatedby')
    op.drop_column('pre_leads', 'createdby')
    op.drop_column('pre_leads', 'company_id')
    op.drop_column('pre_leads', 'lead_score')
    op.drop_column('pre_leads', 'remarks')
    op.drop_column('pre_leads', 'lead_since')
    op.drop_column('pre_leads', 'sales_rep')
    op.drop_column('pre_leads', 'lead_source')
    op.drop_column('pre_leads', 'timezone')
    op.drop_column('pre_leads', 'office_timings')
    op.drop_column('pre_leads', 'region_id')
    op.drop_column('pre_leads', 'industry_id')
    op.drop_column('pre_leads', 'lead_status')
    op.drop_column('pre_leads', 'group_id')
    op.drop_column('pre_leads', 'memo')
    op.drop_column('pre_leads', 'nof_representative')
    op.drop_column('pre_leads', 'fax')
    op.drop_column('pre_leads', 'phone_no')
    op.drop_column('pre_leads', 'state_id')
    op.drop_column('pre_leads', 'country_id')
    op.drop_column('pre_leads', 'zip_code')
    op.drop_column('pre_leads', 'city_id')
    op.drop_column('pre_leads', 'address_line2')
    op.drop_column('pre_leads', 'address_line1')
    # ### end Alembic commands ###
