"""Add new pre_lead fields

Revision ID: 69e6232e176c
Revises: 
Create Date: 2026-01-27 18:54:47.144575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e6232e176c'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use IF NOT EXISTS to handle columns already created by the initial migration
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS city_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS country_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS state_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS phone_no VARCHAR(50)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS fax VARCHAR(50)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS nof_representative VARCHAR(255)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS memo TEXT")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS group_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS lead_status VARCHAR(50)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS industry_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS region_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS office_timings VARCHAR(100)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS timezone VARCHAR(100)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS lead_source VARCHAR(100)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS sales_rep INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS lead_since DATE")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS remarks TEXT")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS lead_score VARCHAR(50)")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS company_id INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS createdby INTEGER")
    op.execute("ALTER TABLE pre_leads ADD COLUMN IF NOT EXISTS updatedby INTEGER")
    op.execute("ALTER TABLE pre_leads ALTER COLUMN phone TYPE VARCHAR(50)")
    op.execute("ALTER TABLE pre_leads ALTER COLUMN alternate_phone TYPE VARCHAR(50)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_leads', 'alternate_phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('pre_leads', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('pre_leads', 'updatedby')
    op.drop_column('pre_leads', 'createdby')
    op.drop_column('pre_leads', 'company_id')
    op.drop_column('pre_leads', 'lead_score')
    op.drop_column('pre_leads', 'remarks')
    op.drop_column('pre_leads', 'lead_since')
    op.drop_column('pre_leads', 'sales_rep')
    op.drop_column('pre_leads', 'lead_source')
    op.drop_column('pre_leads', 'timezone')
    op.drop_column('pre_leads', 'office_timings')
    op.drop_column('pre_leads', 'region_id')
    op.drop_column('pre_leads', 'industry_id')
    op.drop_column('pre_leads', 'lead_status')
    op.drop_column('pre_leads', 'group_id')
    op.drop_column('pre_leads', 'memo')
    op.drop_column('pre_leads', 'nof_representative')
    op.drop_column('pre_leads', 'fax')
    op.drop_column('pre_leads', 'phone_no')
    op.drop_column('pre_leads', 'state_id')
    op.drop_column('pre_leads', 'country_id')
    op.drop_column('pre_leads', 'zip_code')
    op.drop_column('pre_leads', 'city_id')
    op.drop_column('pre_leads', 'address_line2')
    op.drop_column('pre_leads', 'address_line1')
    # ### end Alembic commands ###
