"""add presentation_modules to cr_presentations

Revision ID: 9c3c66cdb0cd
Revises: 2572548d4dc7
Create Date: 2026-02-04 18:33:51.279278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3c66cdb0cd'
down_revision: Union[str, None] = '2572548d4dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cr_presentations', sa.Column('presentation_modules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cr_presentations', 'presentation_modules')
    # ### end Alembic commands ###
