"""Add missing columns to lead_contacts

Revision ID: c84ac7e1ba32
Revises: d5e6f7g8h9i0
Create Date: 2026-02-02 11:03:14.708926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84ac7e1ba32'
down_revision: Union[str, None] = 'd5e6f7g8h9i0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_activities', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_activities', sa.Column('pre_lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lead_activities_company_id'), 'lead_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_pre_lead_id'), 'lead_activities', ['pre_lead_id'], unique=False)
    op.add_column('lead_contacts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_contacts', sa.Column('pre_lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lead_contacts_company_id'), 'lead_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_contacts_pre_lead_id'), 'lead_contacts', ['pre_lead_id'], unique=False)
    op.add_column('lead_documents', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_documents', sa.Column('pre_lead_id', sa.Integer(), nullable=True))
    op.alter_column('lead_documents', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_lead_documents_company_id'), 'lead_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_documents_pre_lead_id'), 'lead_documents', ['pre_lead_id'], unique=False)
    op.create_foreign_key(None, 'lead_documents', 'pre_leads', ['pre_lead_id'], ['id'])
    op.add_column('lead_memos', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_memos', sa.Column('pre_lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lead_memos_company_id'), 'lead_memos', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_memos_pre_lead_id'), 'lead_memos', ['pre_lead_id'], unique=False)
    op.add_column('lead_qualified_profiles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('lead_qualified_profiles', sa.Column('pre_lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lead_qualified_profiles_company_id'), 'lead_qualified_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_qualified_profiles_pre_lead_id'), 'lead_qualified_profiles', ['pre_lead_id'], unique=False)
    op.add_column('pre_lead_contacts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('pre_lead_contacts', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pre_lead_contacts_company_id'), 'pre_lead_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_pre_lead_contacts_lead_id'), 'pre_lead_contacts', ['lead_id'], unique=False)
    op.add_column('pre_lead_memos', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('pre_lead_memos', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pre_lead_memos_company_id'), 'pre_lead_memos', ['company_id'], unique=False)
    op.create_index(op.f('ix_pre_lead_memos_lead_id'), 'pre_lead_memos', ['lead_id'], unique=False)
    op.add_column('qualified_lead_profiles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('qualified_lead_profiles', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_qualified_lead_profiles_company_id'), 'qualified_lead_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_qualified_lead_profiles_lead_id'), 'qualified_lead_profiles', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualified_lead_profiles_lead_id'), table_name='qualified_lead_profiles')
    op.drop_index(op.f('ix_qualified_lead_profiles_company_id'), table_name='qualified_lead_profiles')
    op.drop_column('qualified_lead_profiles', 'lead_id')
    op.drop_column('qualified_lead_profiles', 'company_id')
    op.drop_index(op.f('ix_pre_lead_memos_lead_id'), table_name='pre_lead_memos')
    op.drop_index(op.f('ix_pre_lead_memos_company_id'), table_name='pre_lead_memos')
    op.drop_column('pre_lead_memos', 'lead_id')
    op.drop_column('pre_lead_memos', 'company_id')
    op.drop_index(op.f('ix_pre_lead_contacts_lead_id'), table_name='pre_lead_contacts')
    op.drop_index(op.f('ix_pre_lead_contacts_company_id'), table_name='pre_lead_contacts')
    op.drop_column('pre_lead_contacts', 'lead_id')
    op.drop_column('pre_lead_contacts', 'company_id')
    op.drop_index(op.f('ix_lead_qualified_profiles_pre_lead_id'), table_name='lead_qualified_profiles')
    op.drop_index(op.f('ix_lead_qualified_profiles_company_id'), table_name='lead_qualified_profiles')
    op.drop_column('lead_qualified_profiles', 'pre_lead_id')
    op.drop_column('lead_qualified_profiles', 'company_id')
    op.drop_index(op.f('ix_lead_memos_pre_lead_id'), table_name='lead_memos')
    op.drop_index(op.f('ix_lead_memos_company_id'), table_name='lead_memos')
    op.drop_column('lead_memos', 'pre_lead_id')
    op.drop_column('lead_memos', 'company_id')
    op.drop_constraint(None, 'lead_documents', type_='foreignkey')
    op.drop_index(op.f('ix_lead_documents_pre_lead_id'), table_name='lead_documents')
    op.drop_index(op.f('ix_lead_documents_company_id'), table_name='lead_documents')
    op.alter_column('lead_documents', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lead_documents', 'pre_lead_id')
    op.drop_column('lead_documents', 'company_id')
    op.drop_index(op.f('ix_lead_contacts_pre_lead_id'), table_name='lead_contacts')
    op.drop_index(op.f('ix_lead_contacts_company_id'), table_name='lead_contacts')
    op.drop_column('lead_contacts', 'pre_lead_id')
    op.drop_column('lead_contacts', 'company_id')
    op.drop_index(op.f('ix_lead_activities_pre_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_company_id'), table_name='lead_activities')
    op.drop_column('lead_activities', 'pre_lead_id')
    op.drop_column('lead_activities', 'company_id')
    # ### end Alembic commands ###
